### ISSUE TITLE
problem installing module

### ISSUE THREAD

**Issue by dusans** [wyplay/pytracemalloc#3]
When trying to install the module with
Python-2.7.5\PCbuild\python.exe setup.py install

i get the following error:
Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    main()
  File "setup.py", line 55, in main
    pythonapi = ctypes.cdll.LoadLibrary(None)
  File "Python-2.7.5\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "Python-2.7.5\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: expected string or Unicode object, NoneType found

**Comment by cmuller** [comment]
I am freezing this project. Please report your issue in the official repo https://github.com/haypo/pytracemalloc.
